(function(){
  'use strict'

  angular.module('ToDo')
  .controller(toDoControler,'toDoControler');

  function toDoControler(){
    var vm = this;
    /*====================== Delegation Variables ====================== */
    /*====================== Variables ================================= */
    /*====================== Services ================================= */
    /*====================== Public Methods =========================== */
    /*====================== Private Methods ========================== */

    function init(){

    }
    /*====================== Actions ================================= */
    init();
  }
})();
